name: Haskell CI

on: [push, pull_request]

jobs:
  build:
   
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - uses: haskell-actions/setup@v2
    - name: Build
      run: |
        cabal v2-configure --enable-tests
        cabal v2-build
        mkdir out
        cabal v2-install --installdir="$(pwd)/out"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: barbly
        path: out/barbly
