name: Haskell CI

on: [push]

jobs:
  build:
   
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Install GHC
      run: |
        curl https://gitlab.haskell.org/haskell/ghcup/raw/master/bootstrap-haskell -sSf | sh
    - name: Build
      run: |
        source ~/.ghcup/env
        cabal v2-configure --enable-tests
        cabal v2-build
