name: Haskell CI

on: [push]

jobs:
  build:
   
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Install GHC
      run: |
        curl https://gitlab.haskell.org/haskell/ghcup/raw/master/bootstrap-haskell -sSf | sh
        source ~/.ghcup/env
    - name: Install dependencies
      run: cabal install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal configure --enable-tests
        cabal build
    - name: Run tests
      run: cabal test
